### ISSUE TITLE
move to wrtc version 0.0.55?

### ISSUE THREAD

**Issue by jtj02** [rtc-io/rtc-plugin-node#3]
I am getting an error on npm install from the npm repo. Looks like it would be solved by bumping up the dependency on wrtc to version 0.0.55.

**Comment by silviapfeiffer** [comment]
Can you confirm that that worked?

**Comment by DamonOehlman** [comment]
@jtj02 @silviapfeiffer I think this is a good idea.  I was waiting for a version of `wrtc` to be released that had pre-built packages for linux, etc.  Looks like `0.0.55` does not so I think upgrading to that is a no brainer.

**Comment by silviapfeiffer** [comment]
Cool!
